server:
  port: 11000
spring:
  application:
    name: user-service
  profiles:
    active: @profile.active@
  cloud:
    nacos:
      config:
        server-addr: local.fudges.cn:8848
        file-extension: yaml
        group: BASE_CLOUD_PROJECT
      discovery:
        server-addr: local.fudges.cn:8848
        group: BASE_CLOUD_PROJECT