spring:
  application:
    name: role
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nacos_devtest?useUnicode=true&characterEncoding=utf-8
    username: nacos
    password: nacos