spring:
  application:
    name: role
  profiles:
    active: @profile.active@
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        group: BASE_CLOUD_PROJECT
      discovery:
        server-addr: 127.0.0.1:8848
        group: BASE_CLOUD_PROJECT