spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://local.fudges.cn:13307/nacos_devtest?useUnicode=true&characterEncoding=utf-8
    username: nacos
    password: nacos