spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://local.fudges.cn:13307/cb_role?useUnicode=true&characterEncoding=utf-8
    username: ${FUDGES_MYSQL_USERNAME}
    password: ${FUDGES_MYSQL_PASSWORD}