spring:
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
        namespace: dd881871-af88-4318-994a-1b5f6aefa362
      discovery:
        namespace: dd881871-af88-4318-994a-1b5f6aefa362
  security:
    oauth2:
      client:
        registration:
          messaging-client:
            provider: spring
            client-id: messaging-client
            client-secret: 123456
            client-name: 71fb2b2b-a46d-4bcf-9ba5-8263d4cb0449
            client-authentication-method: client_secret_basic
            redirect-uri: http://127.0.0.1:9000/login/oauth2/code/messaging-client
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - message.read
              - message.write
        provider:
          spring:
            authorization-uri: http://127.0.0.1:9200/oauth2/authorize
            token-uri: http://127.0.0.1:9200/oauth2/token
            jwk-set-uri: http://127.0.0.1:9200/oauth2/jwks
logging:
  level:
    cn.fudges: debug