server:
  port: 9200
spring:
  application:
    name: oauth2-auth-service
  profiles:
    active: @profile.active@
  cloud:
    nacos:
      config:
        server-addr: local.fudges.cn:8848
        file-extension: yaml
        group: BASE_CLOUD_PROJECT
        import-check:
          enabled: false
      discovery:
        server-addr: local.fudges.cn:8848
        group: BASE_CLOUD_PROJECT
jwt:
  private.key: classpath:static/app.key
  public.key: classpath:static/app.pub